#ifndef CHIP_8_TEST_CONSTANTS_HPP_
#define CHIP_8_TEST_CONSTANTS_HPP_

#define TEST_ROM_START_ADDRESS 0x200
#define TEST_RAM_SIZE 0x1000

#define TEST_NUM_REGISTERS 16

#define TEST_OFF_PIXEL 0
#define TEST_ON_PIXEL 1
#define TEST_SCREEN_HEIGHT 32
#define TEST_SCREEN_WIDTH 64
#define TEST_FONT_WIDTH 8

#endif //CHIP_8_TEST_CONSTANTS_HPP_
