#ifndef CHIP_8_INCLUDE_CHIP8CONSTANTS_HPP_
#define CHIP_8_INCLUDE_CHIP8CONSTANTS_HPP_

// Chip8Machine
#define INSTRUCTION_LENGTH 2
#define NUM_V_REGS 16

// Display
#define MAX_HEIGHT 32
#define MAX_WIDTH 64

// Memory
#define RAM_SIZE 0x1000
#define ROM_START_ADDRESS 0x200

#endif  // CHIP_8_INCLUDE_CHIP8CONSTANTS_HPP_
